=== super7ramp/croiseur/crosswords-dictionary/crosswords-dictionary-xml-codec/src/main/resources/dictionary.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
SPDX-FileCopyrightText: 2023 Antoine Belvire
SPDX-License-Identifier: GPL-3.0-or-later
-->

<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/dictionary"
	xmlns:tns="http://www.example.org/dictionary">

	<import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://www.w3.org/2001/xml.xsd" />

	<complexType name="words">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element name="word" type="string" />
		</sequence>
	</complexType>


	<complexType name="dictionary">
		<sequence>
			<element name="locale" type="language" />
			<element name="name" type="tns:translatableString"
				minOccurs="1" maxOccurs="unbounded" />
			<element name="description" type="tns:translatableString"
				minOccurs="1" maxOccurs="unbounded" />
			<element name="words" type="tns:words" />
		</sequence>
	</complexType>

	<complexType name="translatableString">
		<simpleContent>
			<extension base="string">
				<attribute ref="xml:lang" default="en" />
			</extension>
		</simpleContent>
	</complexType>

	<element name="dictionary" type="tns:dictionary">
		<unique name="unique-name-per-lang">
			<selector xpath="name" />
			<field xpath="@xml:lang" />
		</unique>
		<unique name="unique-description-per-lang">
			<selector xpath="description" />
			<field xpath="@xml:lang" />
		</unique>
	</element>
</schema>

=== super7ramp/croiseur/croiseur-dictionary/croiseur-dictionary-xml-codec/src/test/resources/example.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
SPDX-FileCopyrightText: 2023 Antoine Belvire
SPDX-License-Identifier: GPL-3.0-or-later
-->

<tns:dictionary xmlns:tns="http://www.example.org/dictionary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/dictionary dictionary.xsd ">
    <locale>en</locale>
    <name>Dictionary example</name>
    <name xml:lang="fr-FR">Exemple de dictionnaire</name>
    <description>An example of XML dictionary. Useful for discovery and testing purposes.</description>
    <description xml:lang="fr-FR">Un exemple de dictionnaire. Utile à des fins de découverte et de tests.</description>
    <words>
        <word>Hello</word>
        <word>World</word>
    </words>
</tns:dictionary>
